import { validateBoundaryFeatureCollection } from "./validate.js";
import type { BoundaryFeatureCollection, BoundaryLevel, Resolution } from "./types.js";
import type { FetchFn } from "./geoboundaries.js";

const MIRROR_BASE = "https://cdn.jsdelivr.net/gh/layrayson/geo-atlas-data@main/data";

/**
 * Countries mirrored onto our own CDN (github.com/layrayson/geo-atlas-data,
 * served via jsDelivr) instead of fetched live from geoBoundaries.org. This
 * exists because geoBoundaries' download URLs fail CORS when called directly
 * from a browser (see geoboundaries.ts's doc comment, and
 * spikes/04-browser-cors) - the mirror has no such redirect, so countries
 * covered here work in a plain client-side app with zero extra setup, no
 * fetchImpl/proxy required. Countries not yet mirrored still work, but only
 * server-side (or with a caller-provided proxy), same as before.
 *
 * Each mirrored file is already validated and ring-rewound (see
 * scripts/build-mirror.ts) - it's a complete, ready-to-use
 * BoundaryFeatureCollection, including its own `meta`.
 */
const MIRRORED: ReadonlySet<string> = new Set([
  "AFG:admin1:simplified",
  "AGO:admin1:simplified",
  "ALB:admin1:simplified",
  "AND:admin1:simplified",
  "ARE:admin1:simplified",
  "ARG:admin1:simplified",
  "ARM:admin1:simplified",
  "ATG:admin1:simplified",
  "AUS:admin1:simplified",
  "AUT:admin1:simplified",
  "AZE:admin1:simplified",
  "BDI:admin1:simplified",
  "BEL:admin1:simplified",
  "BEN:admin1:simplified",
  "BFA:admin1:simplified",
  "BGD:admin1:simplified",
  "BGR:admin1:simplified",
  "BHR:admin1:simplified",
  "BHS:admin1:simplified",
  "BIH:admin1:simplified",
  "BLR:admin1:simplified",
  "BLZ:admin1:simplified",
  "BOL:admin1:simplified",
  "BRA:admin1:simplified",
  "BRB:admin1:simplified",
  "BRN:admin1:simplified",
  "BTN:admin1:simplified",
  "BWA:admin1:simplified",
  "CAF:admin1:simplified",
  "CAN:admin1:simplified",
  "CHE:admin1:simplified",
  "CHL:admin1:simplified",
  "CHN:admin1:simplified",
  "CIV:admin1:simplified",
  "CMR:admin1:simplified",
  "COD:admin1:simplified",
  "COG:admin1:simplified",
  "COL:admin1:simplified",
  "COM:admin1:simplified",
  "CPV:admin1:simplified",
  "CRI:admin1:simplified",
  "CUB:admin1:simplified",
  "CYP:admin1:simplified",
  "CZE:admin1:simplified",
  "DEU:admin1:simplified",
  "DJI:admin1:simplified",
  "DMA:admin1:simplified",
  "DNK:admin1:simplified",
  "DOM:admin1:simplified",
  "DZA:admin1:simplified",
  "ECU:admin1:simplified",
  "EGY:admin1:simplified",
  "ERI:admin1:simplified",
  "ESP:admin1:simplified",
  "EST:admin1:simplified",
  "ETH:admin1:simplified",
  "FIN:admin1:simplified",
  "FJI:admin1:simplified",
  "FRA:admin1:simplified",
  "FSM:admin1:simplified",
  "GAB:admin1:simplified",
  "GBR:admin1:simplified",
  "GEO:admin1:simplified",
  "GHA:admin1:simplified",
  "GIN:admin1:simplified",
  "GMB:admin1:simplified",
  "GNB:admin1:simplified",
  "GNQ:admin1:simplified",
  "GRC:admin1:simplified",
  "GRD:admin1:simplified",
  "GRL:admin1:simplified",
  "GTM:admin1:simplified",
  "GUY:admin1:simplified",
  "HND:admin1:simplified",
  "HRV:admin1:simplified",
  "HTI:admin1:simplified",
  "HUN:admin1:simplified",
  "IDN:admin1:simplified",
  "IND:admin1:simplified",
  "IRL:admin1:simplified",
  "IRN:admin1:simplified",
  "IRQ:admin1:simplified",
  "ISL:admin1:simplified",
  "ISR:admin1:simplified",
  "ITA:admin1:simplified",
  "JAM:admin1:simplified",
  "JOR:admin1:simplified",
  "JPN:admin1:simplified",
  "KAZ:admin1:simplified",
  "KEN:admin1:simplified",
  "KGZ:admin1:simplified",
  "KHM:admin1:simplified",
  "KIR:admin1:simplified",
  "KNA:admin1:simplified",
  "KOR:admin1:simplified",
  "KWT:admin1:simplified",
  "LAO:admin1:simplified",
  "LBN:admin1:simplified",
  "LBR:admin1:simplified",
  "LBY:admin1:simplified",
  "LCA:admin1:simplified",
  "LIE:admin1:simplified",
  "LKA:admin1:simplified",
  "LSO:admin1:simplified",
  "LTU:admin1:simplified",
  "LUX:admin1:simplified",
  "LVA:admin1:simplified",
  "MAR:admin1:simplified",
  "MCO:admin1:simplified",
  "MDA:admin1:simplified",
  "MDG:admin1:simplified",
  "MDV:admin1:simplified",
  "MEX:admin1:simplified",
  "MHL:admin1:simplified",
  "MKD:admin1:simplified",
  "MLI:admin1:simplified",
  "MLT:admin1:simplified",
  "MMR:admin1:simplified",
  "MNE:admin1:simplified",
  "MNG:admin1:simplified",
  "MOZ:admin1:simplified",
  "MRT:admin1:simplified",
  "MUS:admin1:simplified",
  "MWI:admin1:simplified",
  "MYS:admin1:simplified",
  "NAM:admin1:simplified",
  "NER:admin1:simplified",
  "NGA:admin1:simplified",
  "NIC:admin1:simplified",
  "NIU:admin1:simplified",
  "NLD:admin1:simplified",
  "NOR:admin1:simplified",
  "NPL:admin1:simplified",
  "NRU:admin1:simplified",
  "NZL:admin1:simplified",
  "OMN:admin1:simplified",
  "PAK:admin1:simplified",
  "PAN:admin1:simplified",
  "PER:admin1:simplified",
  "PHL:admin1:simplified",
  "PLW:admin1:simplified",
  "PNG:admin1:simplified",
  "POL:admin1:simplified",
  "PRK:admin1:simplified",
  "PRT:admin1:simplified",
  "PRY:admin1:simplified",
  "PSE:admin1:simplified",
  "QAT:admin1:simplified",
  "ROU:admin1:simplified",
  "RUS:admin1:simplified",
  "RWA:admin1:simplified",
  "SAU:admin1:simplified",
  "SDN:admin1:simplified",
  "SEN:admin1:simplified",
  "SGP:admin1:simplified",
  "SLB:admin1:simplified",
  "SLE:admin1:simplified",
  "SLV:admin1:simplified",
  "SMR:admin1:simplified",
  "SOM:admin1:simplified",
  "SRB:admin1:simplified",
  "SSD:admin1:simplified",
  "STP:admin1:simplified",
  "SUR:admin1:simplified",
  "SVK:admin1:simplified",
  "SVN:admin1:simplified",
  "SWE:admin1:simplified",
  "SWZ:admin1:simplified",
  "SYC:admin1:simplified",
  "SYR:admin1:simplified",
  "TCD:admin1:simplified",
  "TGO:admin1:simplified",
  "THA:admin1:simplified",
  "TJK:admin1:simplified",
  "TKM:admin1:simplified",
  "TLS:admin1:simplified",
  "TON:admin1:simplified",
  "TTO:admin1:simplified",
  "TUN:admin1:simplified",
  "TUR:admin1:simplified",
  "TUV:admin1:simplified",
  "TWN:admin1:simplified",
  "TZA:admin1:simplified",
  "UGA:admin1:simplified",
  "UKR:admin1:simplified",
  "URY:admin1:simplified",
  "USA:admin1:simplified",
  "UZB:admin1:simplified",
  "VCT:admin1:simplified",
  "VEN:admin1:simplified",
  "VNM:admin1:simplified",
  "VUT:admin1:simplified",
  "WSM:admin1:simplified",
  "YEM:admin1:simplified",
  "ZAF:admin1:simplified",
  "ZMB:admin1:simplified",
  "ZWE:admin1:simplified",
]);

export function isMirrored(iso3: string, level: BoundaryLevel, resolution: Resolution): boolean {
  return MIRRORED.has(`${iso3}:${level}:${resolution}`);
}

export async function fetchFromMirror(
  iso3: string,
  level: BoundaryLevel,
  resolution: Resolution,
  fetchImpl: FetchFn
): Promise<BoundaryFeatureCollection> {
  const url = `${MIRROR_BASE}/${iso3}/${level}-${resolution}.geojson`;
  const res = await fetchImpl(url);
  if (!res.ok) {
    throw new Error(`Mirror request to ${url} failed with status ${res.status}`);
  }
  const data = await res.json();
  validateBoundaryFeatureCollection(data);
  return data;
}
